spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  application:
              name:
                  NewsService

