spring:
  liquibase:
    change-log: classpath:/db/migrations/changelog.xml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url:
      jdbc:postgresql://localhost:5432/newsdata
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  application:
              name:
                  NewsService

